# datasets:
#   events:
#     table_name: "default.events_{process_date}"
#     csv_path: "dbfs:/Volumes/de_catalog/raw/shared_data"

runtime:
  mode: databricks   # databricks | local

datasets:
  events:
    databricks:
      table_name: "default.events_{process_date}"
      csv_path: "/Volumes/de_catalog/raw/shared_data"
    local:
      table_name: "default.events_{process_date}"
      csv_path: "data/raw"

